require("sego.plugins")
require("sego.set")
require("sego.keymaps")
require("sego.lsp")
require("sego.plug-settings.cmp")
require("sego.plug-settings.autopairs")
require("sego.plug-settings.lualine")
require("sego.plug-settings.treesitter")
require("sego.plug-settings.nvim-tree")
require("sego.plug-settings.comment")
require("sego.plug-settings.bufferline")
require("sego.plug-settings.gitsigns")
require("sego.plug-settings.toggleterm")

